language: generic

install:
  - git clone --depth 1 --branch v1.5.3 --single-branch https://github.com/thinca/vim-themis /tmp/vim-themis

before_script:
  - vim --version

script:
  - /tmp/vim-themis/bin/themis --reporter spec

